name: Auto-build

on:
  push:
    branches: [ "refactoring", "TEST" ]
  pull_request:
    branches: [ "refactoring" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  msvc:
    name: Build with MSVC
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get DXSDK
      run:  |
            DXDIR=$TEMP/DXDIR
            curl -L https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -o _DX2010_.exe
            7z x _DX2010_.exe DXSDK/Include -o_DX2010_
            7z x _DX2010_.exe DXSDK/Lib/x86 -o_DX2010_
            mkdir $DXDIR
            mv _DX2010_/DXSDK/* $DXDIR
            rm -fR _DX*_ _DX*_.exe
            echo "DXSDK_DIR=$DXDIR" >> $GITHUB_ENV
      shell: bash
    - name: Compile with MSVC
      run: |
        cmake -A Win32 . -B build_msvc
        cmake --build build_msvc
      shell: bash
    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dll_msvc
        path: |
          ${{ github.workspace }}/build_msvc/MatrixGame/Debug/MatrixGame.dll

  gcc:
    name: Build with GCC
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get MinGW
      run: |
           MINGW_DIR=$TEMP/mingw
           curl -L https://github.com/brechtsanders/winlibs_mingw/releases/download/13.1.0-16.0.2-11.0.0-ucrt-r1/winlibs-i686-mcf-dwarf-gcc-13.1.0-mingw-w64ucrt-11.0.0-r1.7z -o mingw.7z
           7z x mingw.7z -o$MINGW_DIR
           rm mingw.7z
           echo "PATH=$MINGW_DIR/mingw32/bin:$PATH" >> $GITHUB_ENV
      shell: bash
    - name: Get Ninja
      run: |
           NINJA_DIR=$TEMP/ninja
           curl -L https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip -o ninja.zip
           unzip ninja.zip -d $NINJA_DIR
           rm ninja.zip
           echo "PATH=$NINJA_DIR:$PATH" >> $GITHUB_ENV
      shell: bash
    - name: Compile with GCC
      run: |
        # ninja wants cmd.exe to be in the path
        export PATH=/c/Windows/System32:$PATH
        cmake . -G "Ninja" -B build_gcc
        cmake --build build_gcc
      shell: bash
    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dll_gcc
        path: |
          ${{ github.workspace }}/build_gcc/MatrixGame/MatrixGame.dll